In [1]:
greeting = 'Hello'
name = 'Buki'
print(greeting + ' ' + name + '!')

Hello Buki!


In [2]:
##multiple lines
print('''Dad: Hello Son, How are you? 
Son: I\'m fine dad. How was yours?''')

Dad: Hello Son, How are you? 
Son: I'm fine dad. How was yours?


In [3]:
##tuple data type
al = 1, 3, 4, 5
print(al)
type(al)

(1, 3, 4, 5)


tuple

In [4]:
##dict data type
pre = dict(Name = ['Olu', 'jas', 'JOjo'],
            Age = [23, 22, 31])
print(pre)

{'Name': ['Olu', 'jas', 'JOjo'], 'Age': [23, 22, 31]}


In [5]:
## find min and max of lists
ax = [12, 34, 50, -2, 0, -4]
ay = [12, 34, 50, -2, 0, -4]
print(ax)
print(ay)
print(min(ax))
print(max(ay))

[12, 34, 50, -2, 0, -4]
[12, 34, 50, -2, 0, -4]
-4
50


In [6]:
## return absoulte numbers 
print(abs(ax[5])) ## convert -4 to 4
print(abs(ay[3])) ## convert -2 to 2
print(ay)

4
2
[12, 34, 50, -2, 0, -4]


In [7]:
##raising to the power 
print(pow(ax[5], 3)) ## i.e -4 multiplied 3x


-64


In [8]:
## find square root of a number
import math
sq = math.sqrt(25)
qr = math.sqrt(10000)

print(sq)
print(qr)

## round numbers up to the highest or down to the nearest number
up = math.ceil(15.55)
down = math.floor(15.55)

print(up)
print(down)

5.0
100.0
16
15


In [9]:
##creating dict data type 
person = {'name' : ['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni'],
           'religion' : ['christian', 'christian', 'christian'],
            'age' : [34, 36, 5], 
          'height' : [112, 122, 60],
            'weight' : [100, 96, 25]}
person

{'name': ['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni'],
 'religion': ['christian', 'christian', 'christian'],
 'age': [34, 36, 5],
 'height': [112, 122, 60],
 'weight': [100, 96, 25]}

In [10]:
## looping
tab = []
for i in person:
    tab.append(i)
    print(tab)
    

['name']
['name', 'religion']
['name', 'religion', 'age']
['name', 'religion', 'age', 'height']
['name', 'religion', 'age', 'height', 'weight']


In [11]:
print(tab)


['name', 'religion', 'age', 'height', 'weight']


In [12]:
##Evaluating conditions
a = 50
b = 23
c = 35
d = 39

In [13]:
##equals to
a == b

False

In [14]:
##less than or equals to
c <= d

True

In [15]:
##greater than or equals to
d >= a

False

In [16]:
##not equals to
b != c

True

In [17]:
a == b or a == c

False

In [18]:
a == b and c

False

In [19]:
a == b and d <= c

False

In [20]:
d >= b or d <= c

True

In [21]:
not a and b == a

False

In [22]:
Tomorrow = 'Thursday'

In [23]:
## replace variable content
Tomorrow.replace('Thur', 'Wedne')
print(Tomorrow)

Thursday


In [24]:
##replace words in a variable but the variable remains the same except you store the replacement in a new variable
Tomorrow.replace('Thur', 'Wedne')

'Wednesday'

In [25]:
Tomorrow

'Thursday'

In [26]:
Next_day = Tomorrow.replace('Thur', 'Wedne')
print(Next_day)

Wednesday


In [27]:
import pandas as pd

In [28]:
x = person['name']
x

['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni']

In [29]:
x[1].upper()

'ADEDOYIN OLADUNNI'

In [30]:
x[1].capitalize()

'Adedoyin oladunni'

In [31]:
x[1].lower()

'adedoyin oladunni'

In [32]:
person

{'name': ['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni'],
 'religion': ['christian', 'christian', 'christian'],
 'age': [34, 36, 5],
 'height': [112, 122, 60],
 'weight': [100, 96, 25]}

In [33]:
##retrieve age data
person.get('age')

[34, 36, 5]

In [34]:
person.get('address')

In [35]:
##retrieve a data, if not in the dict data then python should display 'unknown' instead
person.get('address', 'unknown')

'unknown'

In [36]:
person2 = {'name': 'Adedoyin Oladunni', 'religion': 'christian', 'age': 36, 'height': 122, 'weight': 95}
person2

{'name': 'Adedoyin Oladunni',
 'religion': 'christian',
 'age': 36,
 'height': 122,
 'weight': 95}

In [37]:
random_list = [55, 'lady', 'brown', 'round', 'apple', '-']
random_list

[55, 'lady', 'brown', 'round', 'apple', '-']

In [38]:
another_list = [42, 'man', 'red', 'square', 'berry', '*']
another_list

[42, 'man', 'red', 'square', 'berry', '*']

In [39]:
##merging 2 lists
join = random_list + another_list
print(join)

[55, 'lady', 'brown', 'round', 'apple', '-', 42, 'man', 'red', 'square', 'berry', '*']


In [40]:
## merging 2 lists
random_list.extend(another_list)
print(random_list)

[55, 'lady', 'brown', 'round', 'apple', '-', 42, 'man', 'red', 'square', 'berry', '*']


In [41]:
##check variable type
type(join)

list

In [42]:
alp = ['a', 'd', 'c', 'e', 'b', 'g', 'f']
alp

['a', 'd', 'c', 'e', 'b', 'g', 'f']

In [43]:
##sort list in reverse
alp.sort(reverse = True)
print(alp)

['g', 'f', 'e', 'd', 'c', 'b', 'a']


In [44]:
##sort list alphabetically or numerically
alp.reverse()
print(alp)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [45]:
## sort list
alp.sort()
print(alp)

['a', 'b', 'c', 'd', 'e', 'f', 'g']


In [46]:
##remove data in 1
alp.pop(1)
alp

['a', 'c', 'd', 'e', 'f', 'g']

In [47]:
## remove a from the list
alp.remove('a')
alp

['c', 'd', 'e', 'f', 'g']

In [48]:
##add blue as the last data
alp.append('blue')

In [49]:
#insert all in 6 in the list
alp.insert(6, 'all')
alp

['c', 'd', 'e', 'f', 'g', 'blue', 'all']

In [50]:
##change 1 data to 4
alp[1] = 4
alp

['c', 4, 'e', 'f', 'g', 'blue', 'all']

In [51]:
alp

['c', 4, 'e', 'f', 'g', 'blue', 'all']

In [52]:
tweets = [
    "Wow, what a great day today!! #sunshine",
    "I feel sad about the things going on around us. #covid19",
    "I'm really excited to learn Python with @JovianML #zerotopandas",
    "This is a really nice song. #linkinpark",
    "The python programming language is useful for data science",
    "Why do bad things happen to me?",
    "Apple announces the release of the new iPhone 12. Fans are excited.",
    "Spent my day with family!! #happy",
    "Check out my blog post on common string operations in Python. #zerotopandas",
    "Freecodecamp has great coding tutorials. #skillup"]
tweets

['Wow, what a great day today!! #sunshine',
 'I feel sad about the things going on around us. #covid19',
 "I'm really excited to learn Python with @JovianML #zerotopandas",
 'This is a really nice song. #linkinpark',
 'The python programming language is useful for data science',
 'Why do bad things happen to me?',
 'Apple announces the release of the new iPhone 12. Fans are excited.',
 'Spent my day with family!! #happy',
 'Check out my blog post on common string operations in Python. #zerotopandas',
 'Freecodecamp has great coding tutorials. #skillup']

In [53]:
happy_words = ['great', 'excited', 'happy', 'nice', 'wonderful', 'amazing', 'good', 'best']
happy_words

['great', 'excited', 'happy', 'nice', 'wonderful', 'amazing', 'good', 'best']

In [54]:
sad_words = ['sad', 'bad', 'tragic', 'unhappy', 'worst']
sad_words

['sad', 'bad', 'tragic', 'unhappy', 'worst']

In [55]:
##sort words by the length of the words
def myfunc(e):
    return len(e)

sad_words = ['sad', 'bad', 'tragic', 'unhappy', 'worst']
sad_words.sort(key=myfunc)
print(sad_words)

['sad', 'bad', 'worst', 'tragic', 'unhappy']


In [56]:
print(sad_words)

['sad', 'bad', 'worst', 'tragic', 'unhappy']


In [57]:
compare = []
for x in tweets:
    if 'sad' in x:
        compare.append(x)
        
        print(compare)

['I feel sad about the things going on around us. #covid19']


In [58]:
comparison=[]
for x in happy_words:
    for y in tweets:
        if x in y:
            comparison.append(y)
            
            print(comparison)          

['Wow, what a great day today!! #sunshine']
['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup']
['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup', "I'm really excited to learn Python with @JovianML #zerotopandas"]
['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup', "I'm really excited to learn Python with @JovianML #zerotopandas", 'Apple announces the release of the new iPhone 12. Fans are excited.']
['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup', "I'm really excited to learn Python with @JovianML #zerotopandas", 'Apple announces the release of the new iPhone 12. Fans are excited.', 'Spent my day with family!! #happy']
['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup', "I'm really excited to learn Python with @JovianML #zerotopandas", 'Apple announces the rel

In [59]:
## to print out just the last iteration
print(comparison)

['Wow, what a great day today!! #sunshine', 'Freecodecamp has great coding tutorials. #skillup', "I'm really excited to learn Python with @JovianML #zerotopandas", 'Apple announces the release of the new iPhone 12. Fans are excited.', 'Spent my day with family!! #happy', 'This is a really nice song. #linkinpark']


In [60]:
## to compare and list out similar contents in 2 lists
comp = []
for x in sad_words:
    for y in tweets:
        if x in y:
            comp.append(y)
           

In [61]:
 print(comp)

['I feel sad about the things going on around us. #covid19', 'Why do bad things happen to me?']


In [62]:
## to count number of similar words in 2 lists
x = 0
for i in tweets:
    for j in happy_words:
        if j in i:
            x +=1
            print(x)


1
2
3
4
5
6


In [63]:
##print out the final count, instead of listing out all the iterations
print(x)

6


In [64]:
num_of_sad = 0
for i in sad_words:
    for j in tweets:
        if i in j:
            num_of_sad +=1
            print(num_of_sad)


1
2


In [65]:
#find number of the tweets in the list
len(tweets)

10

In [66]:
cost = 1500
people = 300
ticket = 50
profit = (ticket * people) - cost
print(profit)

13500


In [67]:
number = 0
for x in happy_words:
    for y in tweets:
        if x in y:
            number += 1
            print(number)

1
2
3
4
5
6


In [68]:
number_of_happy_tweets = 0

for word in happy_words:
    for tweet in tweets:
        if word in tweet:
            number_of_happy_tweets +=1
            
            print("Number of happy tweets:", number_of_happy_tweets)

Number of happy tweets: 1
Number of happy tweets: 2
Number of happy tweets: 3
Number of happy tweets: 4
Number of happy tweets: 5
Number of happy tweets: 6


In [69]:
print("Number of happy tweets:", number_of_happy_tweets)

Number of happy tweets: 6


In [70]:
##creating multiple variables once
num, numb, num1 = 3, 4, 6

In [71]:
num == 6

False

In [72]:
numb != 5

True

In [73]:
num >= 2 and num1 == 6

True

In [74]:
num >= 5 and num1 == 6

False

In [75]:
num >= 2 and num1 == 6

True

In [76]:
m = 1
while m <= 100:
    m += 1

In [77]:
print(m)

101


In [78]:
for i in range(15):
    if i % 5 == 0:
        print(i)

0
5
10


In [79]:
for i in range(15):
    if i % 5 == 0:
        i += 1
        print(i)

1
6
11


In [80]:
print(i)

14


In [81]:
##creating reusable function
def greetings(name):
    print('Hello {}, how was your day?'.format(name))

In [82]:
greetings("Olu")

Hello Olu, how was your day?


In [83]:
greetings('Jasmine')

Hello Jasmine, how was your day?


In [84]:
def greeting(name, last_name):
    print('Hello ' + name + ' ' + last_name + ', how was your day?')

In [85]:
greeting('Olu', 'Oladunni')

Hello Olu Oladunni, how was your day?


In [86]:
greeting('Joseline', 'Oladunni')

Hello Joseline Oladunni, how was your day?


## Looping and Functions


In [87]:
def multiplication(x):
    print(x)
    

In [88]:
multiplication(5)

5


In [89]:
def multiplications(x):
    print(x*5)

In [90]:
def functions(x):
    return 5*x


In [91]:
functions(5)

25

In [92]:
print(functions(4))

20


In [93]:
print(functions(15))

75


In [94]:
list = range(1, 20)
list

range(1, 20)

In [95]:
print(list)

range(1, 20)


In [96]:
for i in list:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [97]:
##identifying even numbers in a list
even_list = [2, 14, 7, 5, 8, 9, 12, 18]
result_list = []

for i in even_list:
    if i % 2 == 0:
        result_list.append(i)
        print(result_list)
        

[2]
[2, 14]
[2, 14, 8]
[2, 14, 8, 12]
[2, 14, 8, 12, 18]


In [98]:
##odd numbers in the list
odd_list = [2, 14, 7, 5, 8, 9, 12, 18]
res_list = []

for x in odd_list:
    if x % 2 == 1:
        res_list.append(x)
        
        print(res_list)
        

[7]
[7, 5]
[7, 5, 9]


In [99]:
today = ['Monday', 'Tuesday', 'Wednesday']
for i in today:
    print(i)

Monday
Tuesday
Wednesday


In [100]:
for i in today:
    print(i[2])

n
e
d


In [101]:
today

['Monday', 'Tuesday', 'Wednesday']

In [102]:
today[2]

'Wednesday'

In [103]:
a_number = 23
another_number = 22
a_list = [2, 14, 7, 5, 8, 9, 12, 18]

In [104]:
a_number

if a_number % 2 == 1:
    print('a_number is odd')
else:
    print('a_number is even')

a_number is odd


In [105]:
a_number = 23

if a_number % 2 == 0:
    print('{} is odd'.format(a_number))
    
elif a_number % 2 == 0:
    print('{} is even'.format(a_number))

In [106]:
if another_number % 2 == 0:
    print('{} is divisible by 2'.format(another_number))
elif another_number % 3 == 0:
    print('{} is divisible by 3'.format(another_number))

22 is divisible by 2


In [107]:
if another_number % 3 == 0:
    print('{} is divisible by 3'.format(another_number))
  
elif another_number % 2 == 0:
    print('{} is divisible by 2'.format(another_number))
 
elif another_number % 11 == 0:
    print('{}is divisible by 11'.format(another_number))
    

22 is divisible by 2


In [ ]:
another_number = 55

if another_number % 3 == 0:
    print('{} is divisible by 3'.format(another_number))
elif another_number % 2 == 0:
    print('{} is divisible by 2'.format(another_number))
elif another_number % 11 == 0:
    print('{} is divisible by 11'.format(another_number))
    

In [108]:
x = 0
while x <= 20:
    x += 1
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


## Functions

In [109]:
def emi(amount):
    emi = amount/12
    print('The Equal Monthly Installment payment for this loan is ${}'.format(emi))

In [110]:
emi(12000)

The Equal Monthly Installment payment for this loan is $1000.0


In [111]:
## you can also use return EMI instead of the print statement
def EMI(amount, duration):
    EMI = amount/duration
    print('The Equal Monthly Installment payment for this loan is ${}'.format(EMI))

In [112]:
#10yrs loan is multiplied with 12 months for each year to the EMI
EMI(120000, 10 * 12)

The Equal Monthly Installment payment for this loan is $1000.0


In [113]:
def loan_emi(amount, duration, down_payment = 0):
    loan_amount = amount - down_payment 
    loan_emi = loan_amount/duration
    print('The Equal Monthly Installment payment for this loan is ${}'.format(loan_emi))

In [114]:
loan_emi(1500000, 12 * 12, 300000)

The Equal Monthly Installment payment for this loan is $8333.333333333334


In [115]:
def interest(amount, duration, rate, down_payment = 0):
    loan_amount = amount - down_payment 
    interest = loan_amount * rate * ((1 + rate) ** duration/(((1 + rate) ** duration) - 1))
    print('The Equal Monthly Interest payment for this loan is ${}'.format(interest))

In [116]:
interest(1500000, 12 * 12, 0.08, 300000)

The Equal Monthly Interest payment for this loan is $96001.47658047966


In [117]:
def emi_house(amount, duration, rate, down_payment = 0):
    loan_amount = amount - down_payment 
    emi_house = loan_amount * rate * ((1 + rate) ** duration/(((1 + rate) ** duration) - 1))
    
    print('The Equal Monthly Interest payment for this loan is ${}'.format(emi_house))

In [118]:
## using variables instead
house_price = 15000000
loan_duration = 15 * 12
deposit = 1300000
interest_rate = 0.08

emi_house(house_price, loan_duration, interest_rate, deposit)

The Equal Monthly Interest payment for this loan is $1096001.0556865411


In [ ]:
##automated calculation of loan
Loan_price = float(input('Enter your loan price for the house please:'))
Loan_Duration = float(input('Enter the duration of the please:'))
Deposit = float(input('Enter your down payment for the house please:'))
Interest_rate = float(input('Enter your interest rate please:'))
loan_amount = Loan_price - Deposit
Duration= Loan_Duration * 12
Interest = loan_amount * Interest_rate * ((1 + Interest_rate) ** Duration/(((1 + Interest_rate) ** Duration - 1))

print('The Interest payment for this loan is ${}'.format(Interest))

In [120]:
##automated calculation of BMI
Name = input('Enter your name please:')
Height = float(input('Enter your height in meters please:'))
Weight = float(input('Enter your weight in KG please:'))
BMI = Weight/Height**2

if BMI < 18.5:
    print(f'{Name} you are underweight, your BMI is {BMI}')
elif BMI >= 18.5 and BMI <= 25:
    print(f'{Name} you are Normal weight, your BMI is {BMI}')
else:
    print(f'{Name} you are overweight, your BMI is {BMI}')

Enter your name please:olu
Enter your height in meters please:167
Enter your weight in KG please:90
olu you are underweight, your BMI is 0.003227078776578579


## Numpy


In [121]:
import numpy as np

In [122]:
weights = [0.3, 0.5, 0.7, 0.8]
lagos = [50, 73, 87, 90]
abuja = [12, 30, 58, 39]
kano = [110, 30, 54, 230]

In [123]:
## using zip to create pairs
for i in zip(weights, lagos, abuja, kano):
    print(i)

(0.3, 50, 12, 110)
(0.5, 73, 30, 30)
(0.7, 87, 58, 54)
(0.8, 90, 39, 230)


In [124]:
## multiply  2 lists 
for i, j in zip(weights, lagos):
    print(i * j)
    
## multiply  3 lists 
for i, j, k in zip(weights, lagos, abuja):
    print(i * j * k)

15.0
36.5
60.9
72.0
180.0
1095.0
3532.2
2808.0


In [125]:
##using numpy
weight = np.array([0.3, 0.5, 0.7, 0.8])
lag = np.array([50, 73, 87, 90])
abj = np.array([12, 30, 58, 39])
kanoo = np.array([110, 30, 54, 230])

In [126]:
#check type
print(type(weight))
print(type(lag))
print(type(weights))
print(type(lagos))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'list'>
<class 'list'>


In [127]:
## Numpy Dimension type - 0D array
ad = np.array(42.5)

## 1D array
ac = np.array([50, 73, 87, 90])
am = np.array((50, 73, 87.9, 90))

## 2D array
ab = np.array([[50, 73.1, 87, 90], [51, 83, 77, 17], [31, 33, 67, 53]])
ae = np.array(((50, 73, 87, 90), (51, 83, 77.3, 17), (31, 33, 67, 53)))

## 3D array
at = np.array([[[50, 73, 87, 90], [51, 83, 77, 17]], [[51, 83, 77, 17], [31, 33, 67, 53]]])
av = np.array((((50, 73, 87, 90), (51, 83, 77, 17)), ((51, 83, 77, 17), (31, 33, 67, 53))))

In [128]:
##check dimensional type
print(ad.ndim)
print(ac.ndim)
print(am.ndim)
print(ae.ndim)
print(ab.ndim)
print(at.ndim)
print(av.ndim)


0
1
1
2
2
3
3


In [129]:
##check data type
print(ad.dtype)
print(ac.dtype)
print(am.dtype)
print(ae.dtype)
print(ab.dtype)
print(at.dtype)
print(av.dtype)

float64
int64
float64
float64
float64
int64
int64


In [130]:
##check shape of array
print(ad.shape)
print(ac.shape)
print(am.shape)
print(ae.shape)
print(ab.shape)
print(at.shape)
print(av.shape)

()
(4,)
(4,)
(3, 4)
(3, 4)
(2, 2, 4)
(2, 2, 4)


In [131]:
##access data in the arrays
print(ae[1, 3])
print(ae[1])
print(av[1, 1])
print(av[1, 1, 2])

17.0
[51.  83.  77.3 17. ]
[31 33 67 53]
67


In [132]:
##slicing arrays to access data
print(av[1:])

print(ab[1, 0:3])

[[[51 83 77 17]
  [31 33 67 53]]]
[51. 83. 77.]


In [133]:
## copy arrays
ba = ab.copy()
print(ba)

##change data to new data in an array
ba[2] = [20,  45,  68, 53,]
print(ba)

## to change just one data not the entire array
ba[2, 3] = 10

## view array
ba.view()

[[50.  73.1 87.  90. ]
 [51.  83.  77.  17. ]
 [31.  33.  67.  53. ]]
[[50.  73.1 87.  90. ]
 [51.  83.  77.  17. ]
 [20.  45.  68.  53. ]]


array([[50. , 73.1, 87. , 90. ],
       [51. , 83. , 77. , 17. ],
       [20. , 45. , 68. , 10. ]])

In [134]:
##reshaping arrays to different dimensions
ba
bl = ba.reshape(2, 6) ##2D
bx = ba.reshape(2, 2, 3) ##3D
nc = ba.reshape(4, 3) ##2D

print(bl)
print(bx)
print(nc)
print(nc.ndim)
print(bx.ndim)
print(bl.ndim)

[[50.  73.1 87.  90.  51.  83. ]
 [77.  17.  20.  45.  68.  10. ]]
[[[50.  73.1 87. ]
  [90.  51.  83. ]]

 [[77.  17.  20. ]
  [45.  68.  10. ]]]
[[50.  73.1 87. ]
 [90.  51.  83. ]
 [77.  17.  20. ]
 [45.  68.  10. ]]
2
3
2


In [139]:
##join arrays
ace = np.array([50, 73, 87])
aim = np.array([50, 73, 87])

arr = np.concatenate((ace, aim))
print(arr)

## to change dimension

are = np.concatenate((ace, aim), axis=0)
print(are)

##find null values
np.isnan(arr)
arr

[50 73 87 50 73 87]
[50 73 87 50 73 87]


array([50, 73, 87, 50, 73, 87])

In [140]:
## to create an array from a range and skip ranges 
bp = np.arange(0, 50)
print(bp)
print(np.arange(0, 50, 5))
print(np.arange(0, 50, 3))


##to generate random integer number
print(np.random.randint(50))
print(np.random.rand(50))

## to create an array of float numbers
float = (np.arange(10, dtype = 'f'))
print(float)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[ 0  5 10 15 20 25 30 35 40 45]
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]
28
[0.77932682 0.39988883 0.90810383 0.4779485  0.85905049 0.79460226
 0.6938085  0.58478361 0.86367303 0.65634834 0.15112463 0.43029931
 0.09178923 0.66739861 0.6574113  0.21708186 0.18732987 0.68775474
 0.30985823 0.61560091 0.01622741 0.21169282 0.91302588 0.03874171
 0.54128589 0.84256076 0.55360142 0.50025145 0.19357003 0.13060926
 0.48115686 0.70441171 0.21599088 0.20450142 0.1063451  0.36157607
 0.60942705 0.54787036 0.26386842 0.75138422 0.07838107 0.56107454
 0.7218114  0.02221031 0.45511313 0.44617598 0.09412416 0.33977206
 0.50006811 0.6539851 ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [142]:
##to split array into 3 and 4
print(np.array_split(arr, 3))
print(np.array_split(bl, 4))

## to sort the array numerically or alphabetically
print(np.sort(ace))
print(np.sort(bx))

## to search for a value in an array
arr
print(np.where(arr == 50))
print(np.where(arr != 50))
print(np.where(arr % 2 == 0))

## to search indices
print(np.searchsorted(bp, [3, 40, 7, 60]))

##to find indices/numbers in the array that are not zero
print(np.nonzero(bp))

##to return unique array values
np.unique(arr)

##to union multiple array values
np.union1d(arr, arr)

##

[array([50, 73]), array([87, 50]), array([73, 87])]
[array([[50. , 73.1, 87. , 90. , 51. , 83. ]]), array([[77., 17., 20., 45., 68., 10.]]), array([], shape=(0, 6), dtype=float64), array([], shape=(0, 6), dtype=float64)]
[50 73 87]
[[[50.  73.1 87. ]
  [51.  83.  90. ]]

 [[17.  20.  77. ]
  [10.  45.  68. ]]]
(array([0, 3]),)
(array([1, 2, 4, 5]),)
(array([0, 3]),)
[ 3 40  7 50]
(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),)


array([50, 73, 87])

In [143]:
## carrying out arithemetic functions

aa = np.array([[50,  -73.1, 87],
     [-90,  51,  83],
     [77,  17,  -20],
     [45,  -68,  10]])

ad = np.array([[55,  73.1, 87],
     [9,  51,  83],
     [77,  12,  -20],
     [45,  6,  10]])


print(np.add(ad, aa))
print(np.subtract(ad, aa))
print(np.multiply(ad, aa))
print(np.divide(ad, aa))
print(np.remainder(ad, aa))
print(np.power(ad, aa))
print(np.absolute(ad))


[[105.   0. 174.]
 [-81. 102. 166.]
 [154.  29. -40.]
 [ 90. -62.  20.]]
[[  5.  146.2   0. ]
 [ 99.    0.    0. ]
 [  0.   -5.    0. ]
 [  0.   74.    0. ]]
[[ 2750.   -5343.61  7569.  ]
 [ -810.    2601.    6889.  ]
 [ 5929.     204.     400.  ]
 [ 2025.    -408.     100.  ]]
[[ 1.1        -1.          1.        ]
 [-0.1         1.          1.        ]
 [ 1.          0.70588235  1.        ]
 [ 1.         -0.08823529  1.        ]]
[[  5.  -0.   0.]
 [-81.   0.   0.]
 [  0.  12.  -0.]
 [  0. -62.   0.]]
[[1.04264022e+087 5.59293464e-137 5.47236401e+168]
 [1.31272619e-086 1.21921131e+087 1.92079788e+159]
 [1.81880374e+145 2.21861111e+018 9.53674316e-027]
 [2.48063644e+074 1.21818984e-053 1.00000000e+010]]
[[55.  73.1 87. ]
 [ 9.  51.  83. ]
 [77.  12.  20. ]
 [45.   6.  10. ]]


In [144]:
## arithemetic functions
print(ad / aa)
print(ad * aa)
print(ad - aa)
print(ad + aa)
print(ad % aa)

##comparing arrays
print(ad == aa)
print(ad != aa)
print(ad >= aa)
print(ad <= aa)
print(ad > aa)
print(ad < aa)

[[ 1.1        -1.          1.        ]
 [-0.1         1.          1.        ]
 [ 1.          0.70588235  1.        ]
 [ 1.         -0.08823529  1.        ]]
[[ 2750.   -5343.61  7569.  ]
 [ -810.    2601.    6889.  ]
 [ 5929.     204.     400.  ]
 [ 2025.    -408.     100.  ]]
[[  5.  146.2   0. ]
 [ 99.    0.    0. ]
 [  0.   -5.    0. ]
 [  0.   74.    0. ]]
[[105.   0. 174.]
 [-81. 102. 166.]
 [154.  29. -40.]
 [ 90. -62.  20.]]
[[  5.  -0.   0.]
 [-81.   0.   0.]
 [  0.  12.  -0.]
 [  0. -62.   0.]]
[[False False  True]
 [False  True  True]
 [ True False  True]
 [ True False  True]]
[[ True  True False]
 [ True False False]
 [False  True False]
 [False  True False]]
[[ True  True  True]
 [ True  True  True]
 [ True False  True]
 [ True  True  True]]
[[False False  True]
 [False  True  True]
 [ True  True  True]
 [ True False  True]]
[[ True  True False]
 [ True False False]
 [False False False]
 [False  True False]]
[[False False False]
 [False False False]
 [False  True False]
 [F

In [145]:
##rounding decimal points
arr1= [[55.52,  73.1, 87.25],
     [9.65,  51.16,  83.55],
     [77.45,  12.53,  -20.56],
     [45.76,  6.24,  10.51]]

print(np.trunc(arr1))
print(np.fix(arr1))
print(np.around(arr1))
print(np.floor(arr1))
print(np.ceil(arr1))

[[ 55.  73.  87.]
 [  9.  51.  83.]
 [ 77.  12. -20.]
 [ 45.   6.  10.]]
[[ 55.  73.  87.]
 [  9.  51.  83.]
 [ 77.  12. -20.]
 [ 45.   6.  10.]]
[[ 56.  73.  87.]
 [ 10.  51.  84.]
 [ 77.  13. -21.]
 [ 46.   6.  11.]]
[[ 55.  73.  87.]
 [  9.  51.  83.]
 [ 77.  12. -21.]
 [ 45.   6.  10.]]
[[ 56.  74.  88.]
 [ 10.  52.  84.]
 [ 78.  13. -20.]
 [ 46.   7.  11.]]


In [146]:
z = np.arange(1, 60)
l = np.arange(1, 60, 3)
arr2 = np.array([3, 6, 9])

##multiplying every number in the array
print(np.prod(z))

##adding every number in the array
print(np.sum(z))

##deducting previous number from the next number in the array
print(np.diff(l))

##cummulative multiplication of every number in the array
print(np.cumprod(z))

##cummulative sum of every number in the array
print(np.cumsum(z))

##greatest common denominator in the array
print(np.gcd(arr2))

##lowest common multiple in the array
np.lcm(arr2)
np.lcm.reduce(arr2)

##to return unique and union array values
np.unique(arr)
np.union(arr)

162129586585337856
1770
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
[                   1                    2                    6
                   24                  120                  720
                 5040                40320               362880
              3628800             39916800            479001600
           6227020800          87178291200        1307674368000
       20922789888000      355687428096000     6402373705728000
   121645100408832000  2432902008176640000 -4249290049419214848
 -1250660718674968576  8128291617894825984 -7835185981329244160
  7034535277573963776 -1569523520172457984 -5483646897237262336
 -5968160532966932480 -7055958792655077376 -8764578968847253504
  4999213071378415616 -6045878379276664832  3400198294675128320
  4926277576697053184  6399018521010896896  9003737871877668864
  1096907932701818880  4789013295250014208  2304077777655037952
   -70609262346240000 -2894979756195840000  7538058755741581312
 -7904866829883932672  26739968855884431

TypeError: gcd() takes from 2 to 3 positional arguments but 1 were given

In [156]:
## to sort numpy array
arr1 = arr
np.sort(arr1)
np.flipud(arr1) ##desc order

array([87, 73, 50, 87, 73, 50])

## Pandas

In [157]:
##Create Dataframe with a dict
import pandas as pd


In [158]:
pre = dict(Name = ['Olu', 'jas', 'JOjo'],
            Age = [23, 22, 31])
print(pre)

person = {'name' : ['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni'],
           'religion' : ['christian', 'christian', 'christian'],
            'age' : [34, 36, 5], 
          'height' : [112, 122, 60],
            'weight' : [100, 96, 25]}
print(person)


table = pd.DataFrame(person)
table

{'Name': ['Olu', 'jas', 'JOjo'], 'Age': [23, 22, 31]}
{'name': ['Olubukola Badero', 'Adedoyin Oladunni', 'Jasmine Oladunni'], 'religion': ['christian', 'christian', 'christian'], 'age': [34, 36, 5], 'height': [112, 122, 60], 'weight': [100, 96, 25]}


name   religion  age  height  weight
0   Olubukola Badero  christian   34     112     100
1  Adedoyin Oladunni  christian   36     122      96
2   Jasmine Oladunni  christian    5      60      25

In [159]:
##add new row
table.loc[len(table.index)] = ['Joseline Oladunni', 'christian', 1, 30, 1] 
table.loc[len(table.index)] = ['Olaide Badero', 'christian', 58, 180, 70] 
table.loc[len(table.index)] = ['Adeola Amushan', 'christian', 58, 120, 70]
table

## add new column
table['sex'] = ['Female', 'Male', 'Female', 'Female' , 'Female', 'Female']
table



name   religion  age  height  weight     sex
0   Olubukola Badero  christian   34     112     100  Female
1  Adedoyin Oladunni  christian   36     122      96    Male
2   Jasmine Oladunni  christian    5      60      25  Female
3  Joseline Oladunni  christian    1      30       1  Female
4      Olaide Badero  christian   58     180      70  Female
5     Adeola Amushan  christian   58     120      70  Female

In [160]:

##viewing data in Pandas
table.loc[[1, 2]] ##rows
table.loc[1:5] ##rows
table.loc[table.religion == 'christian']
table.loc[table['weight'] >= 50]
table.loc[(table['weight'] >= 50) & (table['height'] >= 110)] ## & stands for and
table.loc[(table['weight'] <= 50) | (table['height'] >= 110)] ## | stands for or
table['name'] ##columns
table['name'][3] ##field
table.at[3, 'name'] ##field
table.head(5) ##top 5 rows
table.tail(5) ##bottom 5 rows
table[table.religion == 'christian'] ## show all christians
table.loc[table['name'].str.contains('O|ola')] ## find any name with ola or Ola
table.loc[table['name'].str.contains('Olu|Ade'), regex = True] ## find different words using regular expression 
table.loc[table['name'].str.contains('Olu|Ade'), flags = re.I, regex = True] ## retrieve irrespective of capitalisation
table.sample() ##view sample data
table.first_valid_index() ##find the first index without a null value



SyntaxError: invalid syntax (1214093856.py, line 15)

In [161]:
import re
table.loc[table['name'].str.contains('olu|ade'), flags=re.I, regex = True]

SyntaxError: invalid syntax (3078431774.py, line 2)

In [162]:
## basic information about the dataframe
table.info()
table.describe()
table.shape
table.isna()
table.isnull()
table.columns
table.sample(10)
xy = table.copy() ##to copy a dataframe and create a copy in a variable


<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   name      6 non-null      object
 1   religion  6 non-null      object
 2   age       6 non-null      int64 
 3   height    6 non-null      int64 
 4   weight    6 non-null      int64 
 5   sex       6 non-null      object
dtypes: int64(3), object(3)
memory usage: 336.0+ bytes


ValueError: Cannot take a larger sample than population when 'replace=False'

In [163]:
table.loc[len(table.index)] = ['Nan', 'Nan', 'Nan', 'Nan', 'Nan']

##to replace Nan datas in the dataframe with Numpy nan values

table.replace('Nan', np.nan, inplace=True)

##to change column data type
table['weight'] = table['weight'].astype(int)


table

ValueError: cannot set a row with mismatched columns

In [164]:
##arithemetic and comparison operation 
table.weight.sum()
table.weight.sum()/table.height.sum()
table.iloc.[:, 2:5].sum(axis=1)
table.weight.cumsum()
table.weight.mean() ##average
table.weight > 20
table.weight == 20
table[table.weight < 20] ##to view comparison

SyntaxError: invalid syntax (718284908.py, line 4)

In [165]:
##add column
table['BMI'] = table.weight.sum()/table.height.sum()

##drop a column
table.drop(columns = ['BMI'], inplace = True)

##to delete and replace words in a column
table['name'].str.replaces('Olu', 'Ola') ## delete olu and replace it with ola
table['name'].str.replaces('Olu', '') ## delete olu and replace it with nothing

##add new column
table['BMI'] =table.weight/table.height
table

AttributeError: 'StringMethods' object has no attribute 'replaces'

In [166]:
##sort data in ascending and descending order, if in ascending order then set as True
table.sort_values('weight', ascending = False)
table.sort_values(['weight', 'height'], ascending = [False, True])
table.sort_values('weight', ascending = 0)
table.sort_values(['weight', 'Day'], ascending = [0, 1])

KeyError: 'Day'

In [167]:
##to rearrange columns, you can use this opportunity select only columns you want to analyse
table = table[['name', 'DOB', 'age', 'sex', 'weight', 'height', 'BMI', 'Year', 'Month', 'Day', 'religion']]

##to rearrange rows
table.reindex([0, 2, 3, 1, 5, 4])

##to rename column(s)
table.rename(columns = {'old_name':'new_name', 'old_name':'new_name', 'old_name':'new_name'}, inplace = True)


## to tranpose columns to row and row to columns
table.transpose()

## to reset index 
table.reset_index()
table.reset_index(drop = True, inplace = True) ##to drop the old index
table

KeyError: "['DOB', 'BMI', 'Year', 'Month', 'Day'] not in index"

In [168]:
##working with dates
table['DOB'] = ['1988/08/02', '1986/05/09', '2017/10/07', '2021/02/19' , '1964/02/28', '1964/05/29']

##convert non-date column to date data
table['DOB'] = pd.to_datetime(table.DOB)

##to parse date to year, month and day
table['Year'] = pd.DatetimeIndex(table.DOB).year
table['Month'] = pd.DatetimeIndex(table.DOB).month
table['Day'] = pd.DatetimeIndex(table.DOB).day

##to retrieve hour or minutes in timestamps
table.start_time.dt.hour
table.start_time.dt.dayofweek
table.Start_Time.dt.day_name()

table
##now you can analyse what happened in a year, month or day

AttributeError: 'DataFrame' object has no attribute 'start_time'

In [169]:
table.loc[len(table.index)] = ['Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan', 'Nan']

##to replace Nan datas in the dataframe with Numpy nan values, if not showing as null on isna search

table.replace('Nan', np.nan, inplace=True)
table

##to find null values
table.isna().sum().sum()
table.isna().any()

##to find and count duplicate values
table.duplicated()
table.duplicated().sum().sum()

##to drop duplicates
table.drop_duplicates(inplace = True)

##to find unique values
table['religion'].unique()
table.religion.unique()

##to count values in a column
table.name.value_counts()
table.name.count()

##to find correlation
table.corr()

##to. check data type
table.religion.dtype
table['religion'].dtype

##fill null values
table.fillna(130, inplace= True)

##drop null values
table.dropna(inplace= True)
table.dropna(axis=0, inplace= True) ##axis = 0 is for column and 1 is for row
table


ValueError: cannot set a row with mismatched columns

In [170]:
## group data frame 
table.groupby('Year')['weight'].sum()
table.groupby('Month')[['weight', 'height']].sum()
table.groupby('Year')['weight'].count()
table.groupby('Year')['weight'].mean()

##merge two table on a column that they have in common
table.merge(xy, on= 'name') 
table.merge(xy, on= ['name', 'age']) 

##extracting the first letter of the Cabin Number 
titanic_df['Deck_Serial']=titanic_df['Cabin'].str.extract(pat = '([ABCDEFG])')
titanic_df
# extract groups having a vowel followed by
# any character
result = sr.str.extract(pat = '([aeiou].)')

NameError: name 'xy' is not defined

In [ ]:
# create a dictionary using US State code and their corresponding Name
us_states = {'AK': 'Alaska',
 'AL': 'Alabama',
 'AR': 'Arkansas',
 'AS': 'American Samoa',
 'AZ': 'Arizona',
 'CA': 'California',
 'CO': 'Colorado',
 'CT': 'Connecticut',
 'DC': 'District of Columbia',
 'DE': 'Delaware',
 'FL': 'Florida',
 'GA': 'Georgia',
 'GU': 'Guam',
 'HI': 'Hawaii',
 'IA': 'Iowa',
 'ID': 'Idaho',
 'IL': 'Illinois',
 'IN': 'Indiana',
 'KS': 'Kansas',
 'KY': 'Kentucky',
 'LA': 'Louisiana',
 'MA': 'Massachusetts',
 'MD': 'Maryland',
 'ME': 'Maine',
 'MI': 'Michigan',
 'MN': 'Minnesota',
 'MO': 'Missouri',
 'MP': 'Northern Mariana Islands',
 'MS': 'Mississippi',
 'MT': 'Montana',
 'NC': 'North Carolina',
 'ND': 'North Dakota',
 'NE': 'Nebraska',
 'NH': 'New Hampshire',
 'NJ': 'New Jersey',
 'NM': 'New Mexico',
 'NV': 'Nevada',
 'NY': 'New York',
 'OH': 'Ohio',
 'OK': 'Oklahoma',
 'OR': 'Oregon',
 'PA': 'Pennsylvania',
 'PR': 'Puerto Rico',
 'RI': 'Rhode Island',
 'SC': 'South Carolina',
 'SD': 'South Dakota',
 'TN': 'Tennessee',
 'TX': 'Texas',
 'UT': 'Utah',
 'VA': 'Virginia',
 'VI': 'Virgin Islands',
 'VT': 'Vermont',
 'WA': 'Washington',
 'WI': 'Wisconsin',
 'WV': 'West Virginia',
 'WY': 'Wyoming'}

# create a dataframe of State and their corresponding accident cases
state_df = pd.DataFrame(us_accidents['State'].value_counts()).reset_index().rename(columns={'index':'State', 'State':'Cases'})


# Function to convert the State Code with the actual corressponding Name
def convert(x): 
    return us_states[x]

state_df['State'] = state_df['State'].apply(convert)


top_ten_states_name = list(state_df['State'].head(10))


In [ ]:
!pip install opendatasets --upgrade --quiet

csv = pd.read_csv('./us_unemployment_csv')
excel = pd.read_excel('./us_unemployment_xlsx')
txt_file = pd.read_csv('./us_unemployment_csv.txt')