In [1]:
a = [1,2,3,4,5]


In [2]:
a

[1, 2, 3, 4, 5]

In [3]:
a[2:5]

[3, 4, 5]

In [4]:
a[1:][:3]

[2, 3, 4]

In [4]:
a[2:5]=3,5,6

In [5]:
a

[1, 2, 3, 5, 6]

In [6]:
a[2:5]= 'blue', 10, 'red'

In [7]:
a

[1, 2, 'blue', 10, 'red']

In [8]:
a + a

[1, 2, 'blue', 10, 'red', 1, 2, 'blue', 10, 'red']

In [9]:
a

[1, 2, 'blue', 10, 'red']

In [10]:
b = a + a

In [11]:
b

[1, 2, 'blue', 10, 'red', 1, 2, 'blue', 10, 'red']

In [12]:
b.append('baby', 'toddler')

TypeError: list.append() takes exactly one argument (2 given)

In [13]:
b.append('baby')

In [14]:
b

[1, 2, 'blue', 10, 'red', 1, 2, 'blue', 10, 'red', 'baby']

In [15]:
b.insert('pear')

TypeError: insert expected 2 arguments, got 1

In [16]:
b.insert(1, 'pear')

In [17]:
b

[1, 'pear', 2, 'blue', 10, 'red', 1, 2, 'blue', 10, 'red', 'baby']

In [19]:
c = b.copy()

In [20]:
c

[1, 'pear', 2, 'blue', 10, 'red', 1, 2, 'blue', 10, 'red', 'baby']

In [22]:
c.reverse()


In [23]:
c

['baby', 'red', 10, 'blue', 2, 1, 'red', 10, 'blue', 2, 'pear', 1]

In [24]:
c.sort()

TypeError: '<' not supported between instances of 'int' and 'str'

In [32]:
c[:6]

['baby', 'red', 10, 'blue', 2, 1]

In [41]:
type(c)

list

In [39]:
d = {'Name':['olu', 'jas', 'jojo'], 'color':['blue', 'yellow', 'pink'], 'Age':['34', '5', '2']}

In [40]:
d

{'Name': ['olu', 'jas', 'jojo'],
 'color': ['blue', 'yellow', 'pink'],
 'Age': ['34', '5', '2']}

In [36]:
type(d)

dict

In [42]:
type(1.5)

float

In [52]:
d.values()

dict_values([['olu', 'jas', 'jojo'], ['blue', 'yellow', 'pink'], ['34', '5', '2']])

In [53]:
d.keys()

dict_keys(['Name', 'color', 'Age'])

In [54]:
e = d.values()

In [55]:
e

dict_values([['olu', 'jas', 'jojo'], ['blue', 'yellow', 'pink'], ['34', '5', '2']])

In [56]:
type(e)

dict_values

In [69]:
range(10)

range(0, 10)

In [70]:
x = range(10)

In [71]:
x

range(0, 10)

In [74]:
for i in x:
    print('the range is {}'.format(i))

the range is 0
the range is 1
the range is 2
the range is 3
the range is 4
the range is 5
the range is 6
the range is 7
the range is 8
the range is 9


In [81]:
'''dad: Hello how are you? 
son: I'm fine'''

"dad: Hello how are you? \nson: I'm fine"

In [79]:
print('''Dad: Hello Son, How are you? 
Son: I\'m fine dad. How was yours?''')

Dad: Hello Son, How are you? 
Son: I'm fine dad. How was yours?


In [105]:
import numpy as np
from numpy.random import randn
import pandas as pd
from pandas import DataFrame, Series 
import math

In [44]:
deets = DataFrame(d)

In [45]:
deets

Name   color Age
0   olu    blue  34
1   jas  yellow   5
2  jojo    pink   2

In [57]:
e_cop = DataFrame(e)

In [58]:
e_cop

0       1     2
0   olu     jas  jojo
1  blue  yellow  pink
2    34       5     2

In [65]:
e_cop.rename(index={0:'Name', 1:'color', 2:'Age'}, columns={0:'Mum', 1:'first', 2:'last'})

Mum   first  last
Name    olu     jas  jojo
color  blue  yellow  pink
Age      34       5     2

In [66]:
e_cop

0       1     2
0   olu     jas  jojo
1  blue  yellow  pink
2    34       5     2

In [67]:
e_cop = e_cop.rename(index={0:'Name', 1:'color', 2:'Age'}, columns={0:'Mum', 1:'first', 2:'last'})

In [68]:
e_cop

Mum   first  last
Name    olu     jas  jojo
color  blue  yellow  pink
Age      34       5     2

In [84]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [99]:
y=randn(10)

In [101]:
y

array([-0.73374185,  0.42344015, -0.79755327, -0.4188389 , -1.13515364,
        0.92640737,  0.73788044, -0.32388894, -0.83244355,  0.17067083])

In [100]:
abs(y)

array([0.73374185, 0.42344015, 0.79755327, 0.4188389 , 1.13515364,
       0.92640737, 0.73788044, 0.32388894, 0.83244355, 0.17067083])

In [104]:
pow(y, 2)

array([0.53837711, 0.17930156, 0.63609121, 0.17542602, 1.28857379,
       0.85823061, 0.54446755, 0.10490405, 0.69296226, 0.02912853])

In [109]:
np.min(y)

-1.1351536435254195

In [110]:
np.max(y)

0.9264073676297598

In [111]:
np.mean(y)

-0.19832213619273498

In [113]:
s=randn(10)

In [114]:
s

array([ 0.21808581, -0.76731914, -0.42396623,  1.08354821,  0.16578083,
       -0.68915232,  0.29873617, -0.52699337,  0.24628231, -0.22750813])

In [116]:
np.sum(s)

-0.6225058570483779

In [118]:
np.sum(s, y)

TypeError: only integer scalar arrays can be converted to a scalar index

In [117]:
np.add(s, y)

array([-0.51565604, -0.34387899, -1.22151949,  0.66470931, -0.96937281,
        0.23725505,  1.03661661, -0.85088232, -0.58616124, -0.0568373 ])

In [120]:
arr= np.array([1, 2, 3, 4, 5])

In [124]:
arr2= np.array([6,7,8,9,10])

In [131]:
arr + arr2

array([ 7,  9, 11, 13, 15])

In [133]:
arr * arr2

array([ 6, 14, 24, 36, 50])

In [132]:
arr ** arr2

array([      1,     128,    6561,  262144, 9765625])

In [134]:
arr2 / arr

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [135]:
arr / arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [136]:
arr // arr2

array([0, 0, 0, 0, 0])

In [137]:
arr2 // arr

array([6, 3, 2, 2, 2])