What is Deep Learning? This is a subset of Machine Learning that works on the structure and function a human brain. It learns from data that is unstructured and uses complex algorithms to train a neural network.

There is the `input layer` --> `Hidden layer` --> `Output Layer`

The input layer accepts large volume of data as input to build the network and passes it on to the hidden layer. 

The hidden layer processes the data by performing complex operations on the data and carries out `feature extraction`. Then after doing a bunch of computation, the hidden layer passes its values to the output layer.

The output layer then gives its output which could be in the form of a class if we are doing a classification. The output layer generates the predicted output by applying suitable activation functions.

`Top Deep Learning Libraries`
- Keras: Developed by Francois Chollet, an open source library written in Python
- DL4J: Developed by Skymid engineering team and DeepLearning4J community, written in C++ and Java
- Theano: Developed by university of montreal, written in python
- Torch: Developed by Ronan Collobert, Clement Farabet, Koray Kavukcuoglu, written in Python
- TensorFlow: Developed by Google Brain Team, , written in Python, C++ and CUDA


In [481]:
pip install tensorflow --quiet

Note: you may need to restart the kernel to use updated packages.


`Why TensorFlow` 

TensorFlow offers APIs that makes it easier to work on to write code. It supports CPUs and GPUs computing devices. It has a faster compilation time than other Deep Learning libraries.

##### What are Tensors
Tensors are Multi Dimensional arrays. An array is an ordered arrangement of numbers. An image fed to the Model can be represented using assigned numbers arranged in an ordered manner and can be represented in mutiple dimensions.

A 2D or two dimensional array is called a Matrix.

#### Examples of Tensor Dimension
- `8` 0-D/0 Dimension because it contains only one number
- `[2 2 3]` 1-D/1 Dimension because it contains multiple 0-D numbers/tensors

- `[2 2 3]
   [2 4 3]
   [1 2 3]` 2-D/2 Dimension because it contains multiple 1-D tensors
   
- `[2 2 3]
   [2 4 3]`
   
   `[1 2 3]
   [4 2 3]`
   
   `[6 2 3]
   [4 2 3]` 3-D/3 Dimension because it contains multiple 2-D tensors


 


#### Tensor Shapes

- `8` No shape
- `[2 2 3]` 1-D/1 Dimension that has 3 elements/numbers so it is a shape 3 ie (3, )

- `[2 2 3]
   [2 4 3]
   [1 2 3]
   [1 2 3]` 2-D/2 Dimension that has 4 1-D tensors  and 3 elements so it is a 4 by 3 shape ie (4, 3)
   
- `[2 2 3 4]
   [2 4 3 5]
   
   [1 2 3 7]
   [4 2 3 9]
   
   [6 2 3 8]
   [4 2 3 5]` 3-D/3 Dimension that has 3 2-D tensors, 2 1-D tensors and 4 elements so it is a 3 by 2 by 4 shape ie (3, 2, 4)
   
- a 4-D/4 Dimension has multiple 3-D tensors stacked on top of each other

TensorFlow accepts data in the form of multidimensional arrays of higher dimensions called Tensor. 

It works on the basis of Data Flow graphs that have nodes and edges.

Tensor is a generalization of vectors and matrices of potentially higher dimensions. Arrays of data with different dimensions and ranks that are fed as input to the neural networks are called Tensors

Tensor Rank

Each TensorFlow computation is represented a Data Flow graph.

Each node in the graph represents a mathematical operation (add, subtract, multiply etc) and each edge represents multidimensional arrays (Tensors).

Computational Graph is the graph of programming logic which TensorFlow builds in the memory.

`Program Elements in TensorFlow`

**Constants**: These are parameter/variable whose value does not change. You cannot change the value during computation. To define a constant, we use `tf.constant()` command 

Example:

a = tf.constant(2.0, tf.float32) the tf.float32 stipulates data type

b = tf.constant(3.0)

print(a, b)

**Variables**: Allows us to add new trainable parameters to the graph. To define a variable we use `tf.Variable()` command and initialize them before running the graph in a session.

Example:

w = tf.Variable([2.0], dtype=tf.float32) 

b = tf.Variable([-2.0], dtype=tf.float32) 

x = tf.placeholder(tf.float32)

linear_model=w*x+b

**Placeholders**: allows us to feed data to a TensorFlow model from outside a model. It permits a value to be assigned later. To define a placeholder we use `tf.placeholder()` command

Example:
d = tf.placeholder(tf.float64)
e = tf.placeholder(tf.int32)
x = tf.placeholder(tf.float32, shape=(None,5))

a = tf.placeholder(tf.float32)

b = a*2

with tf.Session() as sess:

result = sess.run(b, feed_dict={a:3.0)})

print(result)


**Session**: a session is run to evaluate the nodes. This is called as the TensorFlow runtime.

Example:

a = tf.constant(3.0)

b = tf.constant(2.0)

c = a*b

###### Launch Session 
sess = tf.Session() 

###### Evaluate the tensor c

print(sess.run(c))



In [4]:
import tensorflow as tf

2023-06-14 12:48:24.026608: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [20]:
tf.__version__

'2.12.0'

In [48]:
##this is a variable
zero = tf.Variable(0)
print(zero)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>


In [486]:
##this is a constant
one = tf.constant([[1,1], [1,1]])
print(one)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [488]:
new_value = tf.add(zero,one)
print(new_value)

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [489]:
subtract_value = tf.subtract(zero,one)
print(subtract_value)

tf.Tensor(
[[-1 -1]
 [-1 -1]], shape=(2, 2), dtype=int32)


In [490]:
##create 1-D tensor
tensor_1D = tf.constant([2, 0, -3])
print(tensor_1D)


tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [491]:
##create 2-D tensor
tensor_2D = tf.constant([
    [2, 2, 3],
   [2, 4, 3],
   [1, 2, 3],
   [1, 2, 3]
])
print(tensor_2D)

tf.Tensor(
[[2 2 3]
 [2 4 3]
 [1 2 3]
 [1 2 3]], shape=(4, 3), dtype=int32)


In [492]:
##create 3-D tensor
tensor_3D = tf.constant([
    [[2, 2, 3, 4],
   [2, 4, 3, 6]],
    
   [[1, 2, 3, 7],
   [1, 2, 3, 9]], 
    
   [[4, 5, 3, 89],
   [6, 9, 3, 19]]
])
print(tensor_3D)

tf.Tensor(
[[[ 2  2  3  4]
  [ 2  4  3  6]]

 [[ 1  2  3  7]
  [ 1  2  3  9]]

 [[ 4  5  3 89]
  [ 6  9  3 19]]], shape=(3, 2, 4), dtype=int32)


In [493]:
##create 4-D tensor
tensor_4D = tf.constant([[
    [[2, 2, 3, 4],
   [2, 4, 3, 6]],
    
   [[1, 2, 3, 7],
   [1, 2, 3, 9]], 
    
   [[4, 5, 3, 89],
   [6, 9, 3, 19]]
],

[
    [[2, 2, 3, 4],
   [2, 4, 3, 6]],
    
   [[1, 2, 3, 7],
   [1, 2, 3, 9]], 
    
   [[4, 5, 3, 89],
   [6, 9, 3, 19]]
],

[
    [[2, 2, 3, 4],
   [2, 4, 3, 6]],
    
   [[1, 2, 3, 7],
   [1, 2, 3, 9]], 
    
   [[4, 5, 3, 89],
   [6, 9, 3, 19]]
]

])
print(tensor_4D)

tf.Tensor(
[[[[ 2  2  3  4]
   [ 2  4  3  6]]

  [[ 1  2  3  7]
   [ 1  2  3  9]]

  [[ 4  5  3 89]
   [ 6  9  3 19]]]


 [[[ 2  2  3  4]
   [ 2  4  3  6]]

  [[ 1  2  3  7]
   [ 1  2  3  9]]

  [[ 4  5  3 89]
   [ 6  9  3 19]]]


 [[[ 2  2  3  4]
   [ 2  4  3  6]]

  [[ 1  2  3  7]
   [ 1  2  3  9]]

  [[ 4  5  3 89]
   [ 6  9  3 19]]]], shape=(3, 3, 2, 4), dtype=int32)


In [494]:
## to find a dimensions shape
tensor_3D.shape
tf.shape(tensor_4D)

## to find the rank of a dimension
tf.rank(tensor_4D)

## to find the size
tf.size(fill_tensor, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [71]:
##to change the dtype to float type from int just add a . to one of the numbers
tensor_1D_float = tf.constant([2, 0, -3.])
print(tensor_1D_float)

##to change the dtype just state it in the bracket
float_change = tf.constant([2, 0, -3.], dtype = tf.float32)
print(float_change)

##to change a float to int just cast the float variable
int_change = tf.cast(float_change, dtype = tf.int32)
print(int_change)

##to change a data to bool just cast the data variable
bool_change = tf.cast(float_change, dtype = tf.bool)
print(bool_change)

##tensor string data type
tensor_string = tf.constant([['Hello World', 'Hi baby'], ['Hello World', 'Hi baby']], dtype = tf.string)
print(tensor_string)

tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2.  0. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)
tf.Tensor([ True False  True], shape=(3,), dtype=bool)
tf.Tensor(
[[b'Hello World' b'Hi baby']
 [b'Hello World' b'Hi baby']], shape=(2, 2), dtype=string)


#### Convert a Numpy Array into a tensor

In [72]:
import numpy as np

In [495]:
array = np.array(range(10))
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
 np_tensor = tf.convert_to_tensor(array)
np_tensor

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [496]:
arr = np.eye(3, 3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [497]:
##create tensor eye
eye_tensor = tf.eye(
    num_rows=5,
    num_columns= None, ##if nothing is inserted it will automatically take the value of num_rows
    batch_shape= None, 
    dtype=tf.dtypes.float32, 
    name= None)
eye_tensor
##all of the elements are 0 except the leading diagonal that is 1

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [498]:
##effect of num_columns
eye_tensor_amend = tf.eye(
    num_rows=3,
    num_columns= 4, 
    batch_shape= None, 
    dtype=tf.dtypes.int32, 
    name= None)
eye_tensor_amend*3

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0]], dtype=int32)>

In [88]:
##bool data type
eye_tensor_bool = tf.eye(
    num_rows=3,
    num_columns= 4, 
    batch_shape= None, 
    dtype=tf.dtypes.bool, 
    name= None)
eye_tensor_bool
##all of the elements are false except the leading diagonal that is true


<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])>

In [500]:
##effect of batch_shape
eye_column = tf.eye(
    num_rows=3,
    num_columns= 4, 
    batch_shape= [3], 
    dtype=tf.dtypes.float32, 
    name= None)
eye_column*3
##creates 3D tensor

<tf.Tensor: shape=(3, 3, 4), dtype=float32, numpy=
array([[[3., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 3., 0.]],

       [[3., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 3., 0.]],

       [[3., 0., 0., 0.],
        [0., 3., 0., 0.],
        [0., 0., 3., 0.]]], dtype=float32)>

In [92]:
##create 4D tensor
eye_column = tf.eye(
    num_rows=3,
    num_columns= 4, 
    batch_shape= [2, 4], 
    dtype=tf.dtypes.float32, 
    name= None)
eye_column*3

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]]],


       [[[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]],

        [[3., 0., 0., 0.],
         [0., 3., 0., 0.],
         [0., 0., 3., 0.]]]], dtype=float32)>

In [100]:
##filling a tensor with a specific value
fill_tensor = tf.fill([3,4], 5, name=None)
fill_tensor
##creates a 3 by 4 shape tensor filled with the value 5

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [103]:
##fill the tensor only with the value 1
one_tensor = tf.ones([3, 4, 2], dtype=tf.dtypes.float32)
one_tensor
##creates a 3D shape tensor filled with the value 1

<tf.Tensor: shape=(3, 4, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]], dtype=float32)>

In [501]:
fill_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int32)>

In [107]:
##ones_like creates a tensor of all that has the same shape as the input
ones_like_tensor = tf.ones_like(fill_tensor,  dtype=tf.dtypes.float32)
ones_like_tensor
##fill_tensor was initially a 5 but this changed it all to a 1 and you can change the dtype


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [109]:
numpy_ones = np.ones(10)
numpy_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
np.random

<module 'numpy.random' from '/Users/bad_billipino/opt/anaconda3/lib/python3.9/site-packages/numpy/random/__init__.py'>

In [502]:
##create a random tensor
random_tensor = tf.compat.v1.random_normal(
    [3], 
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None, 
    name=None
)
random_tensor

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [258]:
##changing the mean and stddev dictact where the random numbers should be generated from
mean_tensor = tf.compat.v1.random_normal(
    [5, 5], 
    mean=50.0,
    stddev=100.0,
    dtype=tf.dtypes.float32,
    seed=None, 
    name=None
)
mean_tensor

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [503]:
##randomly generate tensors with a uniform distribution.
uni= tf.compat.v1.random_uniform_initializer(
    minval=0,
    maxval=8,
    seed=None,
    dtype=tf.dtypes.float32
)
uni

In [ ]:
##read on random_set_seed

#### Tensor Indexing - selecting values

In [504]:
tensor_index = tf.constant([0, 1, 2, 3, 4])
tensor_index

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>

In [505]:
tensor_index[0:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [155]:
##select from 0-3 but skips by 2
tensor_index[0:4:2]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2], dtype=int32)>

In [158]:
##selects 3 when it should not have
tensor_index[2:3+1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [159]:
Tensor_2D = tf.constant([[1,2,3], [11,2,3], [1,21,3], [1,2,31]])
Tensor_2D

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [11,  2,  3],
       [ 1, 21,  3],
       [ 1,  2, 31]], dtype=int32)>

In [164]:
##selects just the first column
Tensor_2D[0:2, :1]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 1],
       [11]], dtype=int32)>

In [165]:
##selects just the first and second column
Tensor_2D[0:2, :2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  2],
       [11,  2]], dtype=int32)>

In [166]:
Tensor_3D = tf.constant([[[1,2,3], [11,2,3]], [[1,21,3], [1,2,31]]])
Tensor_3D

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [11,  2,  3]],

       [[ 1, 21,  3],
        [ 1,  2, 31]]], dtype=int32)>

In [173]:
Tensor_3D[0]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [11,  2,  3]], dtype=int32)>

In [172]:
Tensor_3D[0,1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11,  2,  3], dtype=int32)>

In [171]:
Tensor_3D[0,1,1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

### Math Function

In [506]:
mean_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 262.72937  ,  -11.642719 ,  -72.33192  ,   40.891594 ,
         -62.476517 ],
       [  93.39513  ,   49.332306 ,   22.37534  ,  160.37946  ,
          83.43423  ],
       [-162.1885   ,   88.96648  ,  101.31674  ,  -87.09338  ,
          84.44142  ],
       [  47.75511  ,    6.7283554,  -17.817108 ,   13.54287  ,
         103.7507   ],
       [  34.198177 ,  -42.47972  ,  108.91908  ,   -1.6004562,
         -43.08541  ]], dtype=float32)>

In [175]:
##this converts negative values to absolute i.e positive
tf.math.abs(mean_tensor)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[262.72937  ,  11.642719 ,  72.33192  ,  40.891594 ,  62.476517 ],
       [ 93.39513  ,  49.332306 ,  22.37534  , 160.37946  ,  83.43423  ],
       [162.1885   ,  88.96648  , 101.31674  ,  87.09338  ,  84.44142  ],
       [ 47.75511  ,   6.7283554,  17.817108 ,  13.54287  , 103.7507   ],
       [ 34.198177 ,  42.47972  , 108.91908  ,   1.6004562,  43.08541  ]],
      dtype=float32)>

In [176]:
tf.math.abs([-2, 3, -10, -0.1, -0.2])

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 2. ,  3. , 10. ,  0.1,  0.2], dtype=float32)>

In [183]:
##finds square root of the mention element
tf.math.sqrt(
    mean_tensor, name=None
)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[16.20893  ,        nan,        nan,  6.3946533,        nan],
       [ 9.664115 ,  7.023696 ,  4.730258 , 12.664101 ,  9.134233 ],
       [       nan,  9.432204 , 10.065621 ,        nan,  9.189201 ],
       [ 6.910507 ,  2.5939074,        nan,  3.6800637, 10.185809 ],
       [ 5.847921 ,        nan, 10.436431 ,        nan,        nan]],
      dtype=float32)>

In [192]:
##the only allowed values are float so your dtype must be float
sqr = tf.constant([4, 16, 9, 25], dtype=tf.dtypes.float32)
tf.math.sqrt(
    sqr, name=None
)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 4., 3., 5.], dtype=float32)>

In [193]:
tf.sqrt((-2.25)** 2+ 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [205]:
x1 = tf.constant([4, 16, 9, 25])
x2 = tf.constant([4, 16, 9, 25], dtype=tf.dtypes.float32)
x3 = tf.constant([14, 116, 91, 253])
tf.add(x1, x3)
tf.divide(x3, x1)
tf.subtract(x3, x1)
tf.pow(x3, x1)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([     38416,          0, -846579205, -338440611], dtype=int32)>

In [ ]:

tf.math.divide_no_nan(x3, x2)

In [507]:
##to return the index with the maximum value
x_argmax = tf.constant([200, 20, 3000, 50])
x_argmax


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 200,   20, 3000,   50], dtype=int32)>

In [508]:
##the argmax value ie index is found in numpy=
tf.argmax(x_argmax)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [509]:
y_argmax = tf.constant([[200, 20, 300, 50], [14, 116, 911, 253], [14, 116, 91, 253]])
y_argmax

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[200,  20, 300,  50],
       [ 14, 116, 911, 253],
       [ 14, 116,  91, 253]], dtype=int32)>

In [510]:
##to find argmax index of a row data
tf.math.argmax(
    y_argmax[1],
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [227]:
##to find argmin index of a row data
tf.math.argmin(
    y_argmax[1],
    axis=None,
    output_type=tf.dtypes.int64,
    name=None
)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [229]:
y_argmax

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[200,  20, 300,  50],
       [ 14, 116, 911, 253],
       [ 14, 116,  91, 253]], dtype=int32)>

In [228]:
## to find column max index not row
tf.math.argmax(
    y_argmax,
    axis=0,
    output_type=tf.dtypes.int64,
    name=None
)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 1, 1])>

In [230]:
## to find column min index not row
tf.math.argmin(
    y_argmax,
    axis=0,
    output_type=tf.dtypes.int64,
    name=None
)

<tf.Tensor: shape=(4,), dtype=int64, numpy=array([1, 0, 2, 0])>

In [231]:
##used to compare if the two data are the same
tf.math.equal(y_argmax, x_argmax)

<tf.Tensor: shape=(3, 4), dtype=bool, numpy=
array([[ True,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False]])>

In [232]:
##y_argmax raised to power x_argmax
tf.math.pow(y_argmax, x_argmax)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[          0,           0,           0,           0],
       [          0,           0,  1152566401, -1851273783],
       [          0,           0,  -856429023, -1851273783]], dtype=int32)>

In [233]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[8, 16], [2, 3]])
tf.pow(x, y)  
## answer interpreted => [[2**8, 2**16], [3**2, 3**3]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[  256, 65536],
       [    9,    27]], dtype=int32)>

In [238]:
xy = tf.constant([[-2, 2], [3, 3],[8, 16], [2, 3]])
xy

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[-2,  2],
       [ 3,  3],
       [ 8, 16],
       [ 2,  3]], dtype=int32)>

In [241]:
##cumsum, max, min, mean, cumprod
print(tf.math.reduce_min(xy))
print(tf.math.reduce_max(xy))
print(tf.math.reduce_sum(xy))
print(tf.math.reduce_mean(xy))
print(tf.math.reduce_prod(xy))

tf.Tensor(-2, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(-27648, shape=(), dtype=int32)


In [247]:
##changin the axis to 0 fixes the calculations to row
print(tf.math.reduce_max(
    xy, axis=0, keepdims=False, name=None
))

print(tf.math.reduce_min(
    xy, axis=0, keepdims=False, name=None
))

print(tf.math.reduce_sum(
    xy, axis=0, keepdims=False, name=None
))

print(tf.math.reduce_mean(
    xy, axis=0, keepdims=False, name=None
))

tf.Tensor([ 8 16], shape=(2,), dtype=int32)
tf.Tensor([-2  2], shape=(2,), dtype=int32)
tf.Tensor([11 24], shape=(2,), dtype=int32)
tf.Tensor([2 6], shape=(2,), dtype=int32)


In [249]:
##changin the axis to 1 fixes the calculations to column
## you can also change keepdims to true
print(tf.math.reduce_max(
    xy, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_min(
    xy, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_sum(
    xy, axis=1, keepdims=False, name=None
))

print(tf.math.reduce_mean(
    xy, axis=1, keepdims=False, name=None
))

tf.Tensor([ 2  3 16  3], shape=(4,), dtype=int32)
tf.Tensor([-2  3  8  2], shape=(4,), dtype=int32)
tf.Tensor([ 0  6 24  5], shape=(4,), dtype=int32)
tf.Tensor([ 0  3 12  2], shape=(4,), dtype=int32)


In [263]:
tensor_2D

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 2, 3],
       [2, 4, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [264]:
##top_k is used to find the top values matching what we want eg top 10
tf.math.top_k(tensor_2D, k = 2)

##shows the top 2 values and their index

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[3, 2],
       [4, 3],
       [3, 2],
       [3, 2]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[2, 0],
       [1, 2],
       [2, 1],
       [2, 1]], dtype=int32)>)

### Linear Algebra Operations

* This is the study of linear combinations. It is the study of vector spaces, lines and planes, and some mappings that are required to perform the linear transformations. It includes vectors, matrices and linear functions. It is the study of linear sets of equations and its transformation properties

In [511]:
## Multiplies matrix a by matrix b, producing a * b. 
## This is different from the math.multiply or multiply function because that is an element multiplication 
## This is a matrix multiplication
## Note that if a and b matrix have the same shape, matmul will be impossible. The column in a must be same with the row in b
## i.e shape (2, 3) and (2, 3) will not matmul but a (2, 3) and (3, 3) or (2, 3) and (3, 4)  will work

x_1 = tf.constant([[1, 2, 0], 
                   [3, 5, -1]])

x_2 = tf.constant([[1, 2, 0], 
                   [3, 5, -1], 
                   [4, 5, 6]])

print(tf.linalg.matmul(
    x_1,
    x_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    output_type=None,
    name=None
))

print(x_1@x_2) ##this is also a matrix multiplication


tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[  7  12  -2]
 [ 14  26 -11]], shape=(2, 3), dtype=int32)


In [271]:
## Matrix Transpose, rows be column, column becomes rows
## You can write true in the above matmul to transpose
tf.transpose(x_1)
x_2@tf.transpose(x_1) ##perform a matmul whilst transposing the matrix


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5, 13],
       [13, 35],
       [14, 31]], dtype=int32)>

In [276]:
y_1 = tf.constant([[[1,2], [3,5]],
                   [[5,0],[2,0]], 
                   [[10,0], [1,2]]])

y_2 = tf.constant([[[1,4,5],[34,15,1]],
                   [[1,2,2],[3, 5,2]], 
                   [[2, 2, 3], [1,1, 1]]])
print(y_1@y_2)
                                                

tf.Tensor(
[[[ 69  34   7]
  [173  87  20]]

 [[  5  10  10]
  [  2   4   4]]

 [[ 20  20  30]
  [  4   4   5]]], shape=(3, 2, 3), dtype=int32)


* Tensors that are mostly made up of zeros are called `sparse tensors` and TensorFlow has a way of maximizing such types of tensors in the matmul function, view above. If you put true, TensorFlow will take that into consideration and carry out the computation even faster

In [512]:
##Sparse Tensor
T_1 = tf.constant([[1, 0, 0], 
                   [0, 0, -1]])

T_2 = tf.constant([[0, 2, 0], 
                   [0, 0, -1], 
                   [4, 0, 0]])
print(tf.linalg.matmul(
    T_1,
    T_2,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=True,
    b_is_sparse=True,
    output_type=None,
    name=None
))
T_1@T_2

tf.Tensor(
[[ 0  2  0]
 [-4  0  0]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 0,  2,  0],
       [-4,  0,  0]], dtype=int32)>

In [286]:
##Band Part method
## This copies a tensor setting everything outside a central band in each innermost matrix to zero based on certain conditions

band_part = tf.constant([[50, 2, 100], 
                   [3, 5, -1], 
                   [1, 5, 6],
                    [2, 3, 8]], dtype = tf.dtypes.float16)
print(band_part)

##tf.linalg.band_part(input, num_lower, num_upper, name=None)
##(lower<0 or m-n <= 0) and (upper<0 or n-m <= 0)
## m is for rows; n is for columns

print(tf.linalg.band_part(band_part, 0, -1)) ##Upper triangular part will not be 0
print(tf.linalg.band_part(band_part, -1, 0)) ##Lower triangular partwill not be 0
print(tf.linalg.band_part(band_part, 0, 0)) ##Diagonal will not be 0


##try to find a clear exxplanation of this


tf.Tensor(
[[ 50.   2. 100.]
 [  3.   5.  -1.]
 [  1.   5.   6.]
 [  2.   3.   8.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[ 50.   2. 100.]
 [  0.   5.  -1.]
 [  0.   0.   6.]
 [  0.   0.   0.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[50.  0.  0.]
 [ 3.  5.  0.]
 [ 1.  5.  6.]
 [ 2.  3.  8.]], shape=(4, 3), dtype=float16)
tf.Tensor(
[[50.  0.  0.]
 [ 0.  5.  0.]
 [ 0.  0.  6.]
 [ 0.  0.  0.]], shape=(4, 3), dtype=float16)


In [291]:
##inverse function - Computes the inverse of one or more square invertible matrices or their adjoints (conjugate transposes).
##the number of rows and column must be the same to do an inverse
inv_func = tf.constant([[50, 2, 100], 
                   [3, 5, -1], 
                   [1, 5, 6]], dtype= tf.dtypes.float16)
print(inv_func)
tf.linalg.inv(inv_func)


tf.Tensor(
[[ 50.   2. 100.]
 [  3.   5.  -1.]
 [  1.   5.   6.]], shape=(3, 3), dtype=float16)


<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[ 0.01291 ,  0.1799  , -0.185   ],
       [-0.007008,  0.0737  ,  0.129   ],
       [ 0.003687, -0.09143 ,  0.08997 ]], dtype=float16)>

In [300]:
ein_1 = np.array(x_1)


In [299]:
ein_2 = np.array(x_2)

In [301]:
np.matmul(ein_1, ein_2)

array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)

In [307]:
## always insert 'ij,jk->ik' in einsum
np.einsum('ij,jk->ik', ein_1, ein_2)

array([[  7,  12,  -2],
       [ 14,  26, -11]], dtype=int32)

- np.einsum is similar to np.matmul

In [316]:
##Generate random 12 numbers
np.random.rand(12)
##Generate 25 random integer numbers between 1 and 100
np.random.randint(1, 100, 25)

array([21, 53, 73, 85, 11, 69, 85, 54, 75, 78, 79, 33, 84, 75, 91, 15, 96,
       89, 57, 72, 55, 81, 96,  4, 18])

#### Common TensorFlow Functions

In [318]:
tensor_3D

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 2,  2,  3,  4],
        [ 2,  4,  3,  6]],

       [[ 1,  2,  3,  7],
        [ 1,  2,  3,  9]],

       [[ 4,  5,  3, 89],
        [ 6,  9,  3, 19]]], dtype=int32)>

In [324]:
tensor_2D

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 2, 3],
       [2, 4, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [513]:
##This returns a tensor with a length 1 axis inserted at index axis
##specify axis 0-3 depending on the dimension of the tensor
print(tf.expand_dims(tensor_3D, axis=0))
##the shape changes from 3D to 4D

print(tf.expand_dims(tensor_2D, axis=1))
##the shape changes from 2D to 3D



tf.Tensor(
[[[[ 2  2  3  4]
   [ 2  4  3  6]]

  [[ 1  2  3  7]
   [ 1  2  3  9]]

  [[ 4  5  3 89]
   [ 6  9  3 19]]]], shape=(1, 3, 2, 4), dtype=int32)
tf.Tensor(
[[[2 2 3]]

 [[2 4 3]]

 [[1 2 3]]

 [[1 2 3]]], shape=(4, 1, 3), dtype=int32)


In [514]:
##This squeezes the tensor ie opposite of expand
tensor_expanded = tf.expand_dims(tensor_2D, axis=0)
tf.squeeze(tensor_expanded)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 2, 3],
       [2, 4, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [347]:
##This will reshape the tensor to the specified value in the []
##always make sure the multiplication of the original and new tensor are the same
tf.reshape(tensor_expanded,[2,6])


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[2, 2, 3, 2, 4, 3],
       [1, 2, 3, 1, 2, 3]], dtype=int32)>

In [348]:
tf.transpose(tf.reshape(tensor_expanded,[2,6]))

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 2],
       [3, 3],
       [2, 1],
       [4, 2],
       [3, 3]], dtype=int32)>

In [356]:
##Concatenate tensors
concat_1 = tf.constant([[1, 2, 3], [4, 5, 6]])
concat_2 = tf.constant([[10, 8, 9], [5, 6, 7]])

tf.concat([concat_1, concat_2], axis = 0) ##0 means concatenation across the rows

tf.concat([concat_1, concat_2], axis = 1) ##1 means concatenation across the columns


<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3, 10,  8,  9],
       [ 4,  5,  6,  5,  6,  7]], dtype=int32)>

In [364]:

concat_3 = tf.constant([[[1, 2, 3], [5, 6, 7]], [[4, 5, 6], [10, 8, 9]]])
concat_4 = tf.constant([[[10, 8, 9], [5, 6, 7]], [[4, 5, 6], [10, 8, 9]]])
tf.concat([concat_3, concat_4], axis = 0) ##0 for row


<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [10,  8,  9],
        [ 5,  6,  7]],

       [[ 4,  5,  6],
        [10,  8,  9],
        [ 4,  5,  6],
        [10,  8,  9]]], dtype=int32)>

In [361]:
tf.stack([concat_1, concat_2])
tf.stack([concat_1, concat_2], axis=0) ##0 means creating a new axis
tf.stack([concat_1, concat_2], axis=1) 


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [10,  8,  9]],

       [[ 4,  5,  6],
        [ 5,  6,  7]]], dtype=int32)>

In [383]:
##padding a tensor with zeros or a number of your choice ie surround it with 0 or any number
padding = tf.constant([[ 2,  4],
        [ 2,  2]]) 
print(padding)

##the padding value must have columns only to work
##the tensor values being surrounded is written first and 
##the number of rows and columns to surround is stated second 
##ie [2rows above, 4 rows below, 2 0s to the right, 2 0s to the lefts]

tf.pad( concat_1, padding, 'CONSTANT', constant_values=5)
tf.pad( concat_2, padding, 'CONSTANT', constant_values=0)


tf.Tensor(
[[2 4]
 [2 2]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(8, 7), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 10,  8,  9,  0,  0],
       [ 0,  0,  5,  6,  7,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]], dtype=int32)>

In [385]:
concat_1[1, 1:2+1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6], dtype=int32)>

In [391]:
concat_1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [390]:
##this is similar to indexing and slicing
tf.gather(concat_1,[1, 1])
tf.gather(concat_1,[1, 0], axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 1],
       [5, 4]], dtype=int32)>

In [392]:
tensor_3D

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 2,  2,  3,  4],
        [ 2,  4,  3,  6]],

       [[ 1,  2,  3,  7],
        [ 1,  2,  3,  9]],

       [[ 4,  5,  3, 89],
        [ 6,  9,  3, 19]]], dtype=int32)>

In [402]:
tf.gather(tensor_3D,[1, 2])

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  7],
        [ 1,  2,  3,  9]],

       [[ 4,  5,  3, 89],
        [ 6,  9,  3, 19]]], dtype=int32)>

In [401]:
tf.gather(tensor_3D,[1], axis=1)

<tf.Tensor: shape=(3, 1, 4), dtype=int32, numpy=
array([[[ 2,  4,  3,  6]],

       [[ 1,  2,  3,  9]],

       [[ 6,  9,  3, 19]]], dtype=int32)>

In [404]:
tensor_3D

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 2,  2,  3,  4],
        [ 2,  4,  3,  6]],

       [[ 1,  2,  3,  7],
        [ 1,  2,  3,  9]],

       [[ 4,  5,  3, 89],
        [ 6,  9,  3, 19]]], dtype=int32)>

In [408]:
indices = [[1], [0]]
params =[['a', 'b'], 
         ['c', 'd'], 
         ['e', 'f']]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c', b'd'],
       [b'a', b'b']], dtype=object)>

In [409]:
tf.gather(params, indices)

<tf.Tensor: shape=(2, 1, 2), dtype=string, numpy=
array([[[b'c', b'd']],

       [[b'a', b'b']]], dtype=object)>

In [421]:
indice = [[1, 0], [0, 1]]
param =[[1, 2], 
         [3, 4], 
         [5, 6]]
tf.gather_nd(param, indice)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [423]:
indicee = [[1, 0], [0, 1]]
paraam =[['hello', 'hi'], 
         ['deep', 'low'], 
         ['breathe', 'poor']]
tf.gather_nd(paraam, indicee, batch_dims = 0)

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'deep', b'hi'], dtype=object)>

### Ragged Tensors
* Tensors are meant to be rectangular in shape, if not, you will get an error message. However if you wish to create a tensor that is not rectangular and not get an error message, use `tf.ragged.constant()`

In [424]:
##Normal expected tensor
tensor_2D

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[2, 2, 3],
       [2, 4, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>

In [429]:
tensor_two_D = [[2, 2],
       [2, 4, 3, 5],
       [9, 2, 3],
       [1, 2, 3, 7]]
tensor_ragged = tf.ragged.constant(tensor_two_D)
tensor_ragged


<tf.RaggedTensor [[2, 2], [2, 4, 3, 5], [9, 2, 3], [1, 2, 3, 7]]>

In [430]:
tensor_ragged.shape

TensorShape([4, None])

#### Sparse Tensors
* Tensors that contain many zeros

`tf.sparse.SparseTensor([indices], [values], [dense_shape])`

In [440]:
tensor_sparse = tf.sparse.SparseTensor([[1, 1], [3, 4]], values= [11, 56], 
                       dense_shape=[5, 6])

tf.sparse.to_dense(tensor_sparse)

## 

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 56,  0],
       [ 0,  0,  0,  0,  0,  0]], dtype=int32)>

#### String Tensors

In [443]:
tensor_string = tf.constant([['hello', 'hi'], 
         ['deep', 'low'], 
         ['breathe', 'poor']])
tensor_string

<tf.Tensor: shape=(3, 2), dtype=string, numpy=
array([[b'hello', b'hi'],
       [b'deep', b'low'],
       [b'breathe', b'poor']], dtype=object)>

In [446]:
tensor_strings = tf.constant(['hello', 'hi', 'deep', 'low'])
tensor_strings

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'hello', b'hi', b'deep', b'low'], dtype=object)>

In [449]:
tf.strings.join(tensor_string, separator = ' ')

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'hello deep breathe', b'hi low poor'], dtype=object)>

In [448]:
tf.strings.join(tensor_strings, separator = ' ')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello hi deep low'>

In [452]:
tf.strings.lower(tensor_strings)
tf.strings.upper(tensor_strings)
tf.strings.strip(tensor_strings)

<tf.Tensor: shape=(4,), dtype=string, numpy=array([b'hello', b'hi', b'deep', b'low'], dtype=object)>

### Tensor Variables

In [455]:
x_var = tf.Variable(x, name='var1')
print(x_var)

<tf.Variable 'var1:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 2],
       [3, 3]], dtype=int32)>


In [460]:
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 3]], dtype=int32)>

In [ ]:
tf.Variable(
    initial_value=None,
    trainable=None ##this speacifies if during the training the variable will be trainable or not, if true then you can update the variable,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)


**x_var.assign(new_value) will be used to change the value of the variable**

In [461]:
x_var.assign([[2, 3],
       [5, 6]])

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [465]:
x_var.assign_add([[2, 3],
       [2, 1]]) ##to add or subtract a value, use the same shape of numbers


<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[4, 6],
       [7, 7]], dtype=int32)>

In [468]:
x_var.assign_sub([[1, 2],
       [2, 1]])##you can only us same data type 

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[2, 2],
       [3, 5]], dtype=int32)>

In [475]:
##to change device type to CPU, GPU OR TPU
with tf.device('CPU:0'):
    x_1 = tf.constant([1, 2, 3, 4])
    x_2 = tf.constant([1])
    
with tf.device('GPU:0'):
    x_3 = x_1 + x_2 
    
print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 3 4 5], shape=(4,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0


In [473]:
##to change device type to CPU, GPU OR TPU
with tf.device('CPU:0'):
    x_varr = tf.Variable([1,2,3,4])
with tf.device('GPU:0'):
    x_tensor = tf.constant(0.2)
    
    
print(x_varr.device)
print(x_tensor.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [26]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 10s 1us/step


In [29]:
mnist

<module 'keras.api._v2.keras.datasets.mnist' from '/Users/bad_billipino/opt/anaconda3/lib/python3.9/site-packages/keras/api/_v2/keras/datasets/mnist/__init__.py'>

In [28]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [27]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [33]:
##Normalize the data
x_train, x_test = x_train/255.0, x_test/255.0

In [32]:
x_train

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       ...,

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0.

### Building a ML Model

In [39]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [36]:
model

### Training and Evaluating the Model

In [46]:
##You must compile your model before training/testing. Use `model.compile(optimizer, loss)`
model.compile(optimizer = optimizers.SGD(), loss = 'mse', metrics = ['mse'])
model.fit(x_train, y_train, epochs = 5)
model.evaluate(x_test, y_test)
probability_model = tf.keras.Sequential([model, tf.keras.models.Softmax()])


NameError: name 'optimizers' is not defined

In [ ]:
model.evaluate(x_test, y_test)

In [ ]:
probability_model = tf.keras.Sequential([model, tf.keras.models.Softmax()])
